[2025-02-17T16:22:22.133+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: xkcd_comics_ingestion.process_comic_data scheduled__2025-02-14T10:00:00+00:00 [queued]>
[2025-02-17T16:22:22.137+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: xkcd_comics_ingestion.process_comic_data scheduled__2025-02-14T10:00:00+00:00 [queued]>
[2025-02-17T16:22:22.137+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 2
[2025-02-17T16:22:22.143+0000] {taskinstance.py:1380} INFO - Executing <Task(PythonOperator): process_comic_data> on 2025-02-14 10:00:00+00:00
[2025-02-17T16:22:22.145+0000] {standard_task_runner.py:57} INFO - Started process 197 to run task
[2025-02-17T16:22:22.147+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'xkcd_comics_ingestion', 'process_comic_data', 'scheduled__2025-02-14T10:00:00+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/xkcd-comics-dag.py', '--cfg-path', '/tmp/tmp467hq3y0']
[2025-02-17T16:22:22.148+0000] {standard_task_runner.py:85} INFO - Job 3: Subtask process_comic_data
[2025-02-17T16:22:22.155+0000] {logging_mixin.py:151} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-02-17T16:22:22.171+0000] {task_command.py:415} INFO - Running <TaskInstance: xkcd_comics_ingestion.process_comic_data scheduled__2025-02-14T10:00:00+00:00 [running]> on host 09ec2b1d5e6c
[2025-02-17T16:22:22.202+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='xkcd_comics_ingestion' AIRFLOW_CTX_TASK_ID='process_comic_data' AIRFLOW_CTX_EXECUTION_DATE='2025-02-14T10:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-02-14T10:00:00+00:00'
[2025-02-17T16:22:22.202+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
TypeError: process_comic() missing 1 required positional argument: 'comic_data'
[2025-02-17T16:22:22.205+0000] {taskinstance.py:1398} INFO - Marking task as UP_FOR_RETRY. dag_id=xkcd_comics_ingestion, task_id=process_comic_data, execution_date=20250214T100000, start_date=20250217T162222, end_date=20250217T162222
[2025-02-17T16:22:22.209+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 3 for task process_comic_data (process_comic() missing 1 required positional argument: 'comic_data'; 197)
[2025-02-17T16:22:22.245+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-02-17T16:22:22.255+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
