[2025-03-03T12:52:14.308+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: xkcd_dbt_transformations.dbt_debug manual__2025-03-03T12:52:09.290601+00:00 [queued]>
[2025-03-03T12:52:14.312+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: xkcd_dbt_transformations.dbt_debug manual__2025-03-03T12:52:09.290601+00:00 [queued]>
[2025-03-03T12:52:14.312+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 2
[2025-03-03T12:52:14.318+0000] {taskinstance.py:1380} INFO - Executing <Task(BashOperator): dbt_debug> on 2025-03-03 12:52:09.290601+00:00
[2025-03-03T12:52:14.320+0000] {standard_task_runner.py:57} INFO - Started process 274 to run task
[2025-03-03T12:52:14.322+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'xkcd_dbt_transformations', 'dbt_debug', 'manual__2025-03-03T12:52:09.290601+00:00', '--job-id', '97', '--raw', '--subdir', 'DAGS_FOLDER/xkcd_dbt_transformations.py', '--cfg-path', '/tmp/tmp09ir45by']
[2025-03-03T12:52:14.324+0000] {standard_task_runner.py:85} INFO - Job 97: Subtask dbt_debug
[2025-03-03T12:52:14.344+0000] {task_command.py:415} INFO - Running <TaskInstance: xkcd_dbt_transformations.dbt_debug manual__2025-03-03T12:52:09.290601+00:00 [running]> on host e42a692d6092
[2025-03-03T12:52:14.373+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='xkcd_dbt_transformations' AIRFLOW_CTX_TASK_ID='dbt_debug' AIRFLOW_CTX_EXECUTION_DATE='2025-03-03T12:52:09.290601+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-03T12:52:09.290601+00:00'
[2025-03-03T12:52:14.374+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-03-03T12:52:14.374+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'cd /opt/dbt && dbt debug --no-use-colors']
[2025-03-03T12:52:14.377+0000] {subprocess.py:86} INFO - Output:
[2025-03-03T12:52:14.378+0000] {subprocess.py:93} INFO - /bin/bash: line 1: dbt: command not found
[2025-03-03T12:52:14.378+0000] {subprocess.py:97} INFO - Command exited with return code 127
[2025-03-03T12:52:14.382+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2025-03-03T12:52:14.384+0000] {taskinstance.py:1398} INFO - Marking task as UP_FOR_RETRY. dag_id=xkcd_dbt_transformations, task_id=dbt_debug, execution_date=20250303T125209, start_date=20250303T125214, end_date=20250303T125214
[2025-03-03T12:52:14.389+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 97 for task dbt_debug (Bash command failed. The command returned a non-zero exit code 127.; 274)
[2025-03-03T12:52:14.421+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-03-03T12:52:14.432+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
