[2025-03-03T12:42:39.859+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: xkcd_dbt_transformations.dbt_debug manual__2025-03-03T12:39:20.767843+00:00 [queued]>
[2025-03-03T12:42:39.862+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: xkcd_dbt_transformations.dbt_debug manual__2025-03-03T12:39:20.767843+00:00 [queued]>
[2025-03-03T12:42:39.862+0000] {taskinstance.py:1359} INFO - Starting attempt 2 of 3
[2025-03-03T12:42:39.867+0000] {taskinstance.py:1380} INFO - Executing <Task(BashOperator): dbt_debug> on 2025-03-03 12:39:20.767843+00:00
[2025-03-03T12:42:39.869+0000] {standard_task_runner.py:57} INFO - Started process 305 to run task
[2025-03-03T12:42:39.870+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'xkcd_dbt_transformations', 'dbt_debug', 'manual__2025-03-03T12:39:20.767843+00:00', '--job-id', '90', '--raw', '--subdir', 'DAGS_FOLDER/xkcd_dbt_transformations.py', '--cfg-path', '/tmp/tmpxvqr2zdm']
[2025-03-03T12:42:39.872+0000] {standard_task_runner.py:85} INFO - Job 90: Subtask dbt_debug
[2025-03-03T12:42:39.889+0000] {task_command.py:415} INFO - Running <TaskInstance: xkcd_dbt_transformations.dbt_debug manual__2025-03-03T12:39:20.767843+00:00 [running]> on host 9a8b57a0aa30
[2025-03-03T12:42:39.917+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='xkcd_dbt_transformations' AIRFLOW_CTX_TASK_ID='dbt_debug' AIRFLOW_CTX_EXECUTION_DATE='2025-03-03T12:39:20.767843+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-03T12:39:20.767843+00:00'
[2025-03-03T12:42:39.918+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-03-03T12:42:39.918+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'cd /opt/dbt && dbt debug --no-use-colors']
[2025-03-03T12:42:39.922+0000] {subprocess.py:86} INFO - Output:
[2025-03-03T12:42:39.922+0000] {subprocess.py:93} INFO - /bin/bash: line 1: dbt: command not found
[2025-03-03T12:42:39.922+0000] {subprocess.py:97} INFO - Command exited with return code 127
[2025-03-03T12:42:39.927+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2025-03-03T12:42:39.928+0000] {taskinstance.py:1398} INFO - Marking task as UP_FOR_RETRY. dag_id=xkcd_dbt_transformations, task_id=dbt_debug, execution_date=20250303T123920, start_date=20250303T124239, end_date=20250303T124239
[2025-03-03T12:42:39.933+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 90 for task dbt_debug (Bash command failed. The command returned a non-zero exit code 127.; 305)
[2025-03-03T12:42:39.970+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-03-03T12:42:39.981+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
