[2025-02-17T17:33:26.056+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: xkcd_comics.create_table scheduled__2025-02-14T10:00:00+00:00 [queued]>
[2025-02-17T17:33:26.059+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: xkcd_comics.create_table scheduled__2025-02-14T10:00:00+00:00 [queued]>
[2025-02-17T17:33:26.059+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 4
[2025-02-17T17:33:26.064+0000] {taskinstance.py:1380} INFO - Executing <Task(PythonOperator): create_table> on 2025-02-14 10:00:00+00:00
[2025-02-17T17:33:26.066+0000] {standard_task_runner.py:57} INFO - Started process 180 to run task
[2025-02-17T17:33:26.067+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'xkcd_comics', 'create_table', 'scheduled__2025-02-14T10:00:00+00:00', '--job-id', '2', '--raw', '--subdir', 'DAGS_FOLDER/xkcd-comics-dag.py', '--cfg-path', '/tmp/tmpu25gds7b']
[2025-02-17T17:33:26.068+0000] {standard_task_runner.py:85} INFO - Job 2: Subtask create_table
[2025-02-17T17:33:26.073+0000] {logging_mixin.py:151} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-02-17T17:33:26.087+0000] {task_command.py:415} INFO - Running <TaskInstance: xkcd_comics.create_table scheduled__2025-02-14T10:00:00+00:00 [running]> on host ec6302870777
[2025-02-17T17:33:26.118+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='xkcd_comics' AIRFLOW_CTX_TASK_ID='create_table' AIRFLOW_CTX_EXECUTION_DATE='2025-02-14T10:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-02-14T10:00:00+00:00'
[2025-02-17T17:33:26.123+0000] {xkcd-comics-dag.py:41} INFO - comics Table created successfully!
[2025-02-17T17:33:26.124+0000] {xkcd-comics-dag.py:51} INFO - comics Table exists: True
[2025-02-17T17:33:26.125+0000] {python.py:194} INFO - Done. Returned value was: None
[2025-02-17T17:33:26.128+0000] {taskinstance.py:1398} INFO - Marking task as SUCCESS. dag_id=xkcd_comics, task_id=create_table, execution_date=20250214T100000, start_date=20250217T173326, end_date=20250217T173326
[2025-02-17T17:33:26.167+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2025-02-17T17:33:26.177+0000] {taskinstance.py:2776} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-02-18T12:18:17.442+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: xkcd_comics.create_table scheduled__2025-02-14T10:00:00+00:00 [queued]>
[2025-02-18T12:18:17.445+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: xkcd_comics.create_table scheduled__2025-02-14T10:00:00+00:00 [queued]>
[2025-02-18T12:18:17.445+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 4
[2025-02-18T12:18:17.450+0000] {taskinstance.py:1380} INFO - Executing <Task(PythonOperator): create_table> on 2025-02-14 10:00:00+00:00
[2025-02-18T12:18:17.452+0000] {standard_task_runner.py:57} INFO - Started process 185 to run task
[2025-02-18T12:18:17.454+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'xkcd_comics', 'create_table', 'scheduled__2025-02-14T10:00:00+00:00', '--job-id', '2', '--raw', '--subdir', 'DAGS_FOLDER/xkcd-comics-dag.py', '--cfg-path', '/tmp/tmp4undskma']
[2025-02-18T12:18:17.455+0000] {standard_task_runner.py:85} INFO - Job 2: Subtask create_table
[2025-02-18T12:18:17.461+0000] {logging_mixin.py:151} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-02-18T12:18:17.474+0000] {task_command.py:415} INFO - Running <TaskInstance: xkcd_comics.create_table scheduled__2025-02-14T10:00:00+00:00 [running]> on host 666159ec39b4
[2025-02-18T12:18:17.506+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='xkcd_comics' AIRFLOW_CTX_TASK_ID='create_table' AIRFLOW_CTX_EXECUTION_DATE='2025-02-14T10:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-02-14T10:00:00+00:00'
[2025-02-18T12:18:17.511+0000] {xkcd-comics-dag.py:41} INFO - comics Table created successfully!
[2025-02-18T12:18:17.511+0000] {xkcd-comics-dag.py:51} INFO - comics Table exists: True
[2025-02-18T12:18:17.512+0000] {python.py:194} INFO - Done. Returned value was: None
[2025-02-18T12:18:17.515+0000] {taskinstance.py:1398} INFO - Marking task as SUCCESS. dag_id=xkcd_comics, task_id=create_table, execution_date=20250214T100000, start_date=20250218T121817, end_date=20250218T121817
[2025-02-18T12:18:17.555+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2025-02-18T12:18:17.566+0000] {taskinstance.py:2776} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-02-18T12:32:53.954+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: xkcd_comics.create_table scheduled__2025-02-14T10:00:00+00:00 [queued]>
[2025-02-18T12:32:53.958+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: xkcd_comics.create_table scheduled__2025-02-14T10:00:00+00:00 [queued]>
[2025-02-18T12:32:53.958+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 4
[2025-02-18T12:32:53.963+0000] {taskinstance.py:1380} INFO - Executing <Task(PythonOperator): create_table> on 2025-02-14 10:00:00+00:00
[2025-02-18T12:32:53.965+0000] {standard_task_runner.py:57} INFO - Started process 174 to run task
[2025-02-18T12:32:53.967+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'xkcd_comics', 'create_table', 'scheduled__2025-02-14T10:00:00+00:00', '--job-id', '2', '--raw', '--subdir', 'DAGS_FOLDER/xkcd-comics-dag.py', '--cfg-path', '/tmp/tmptqaidxd6']
[2025-02-18T12:32:53.968+0000] {standard_task_runner.py:85} INFO - Job 2: Subtask create_table
[2025-02-18T12:32:53.974+0000] {logging_mixin.py:151} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-02-18T12:32:53.988+0000] {task_command.py:415} INFO - Running <TaskInstance: xkcd_comics.create_table scheduled__2025-02-14T10:00:00+00:00 [running]> on host 44c469aaa67a
[2025-02-18T12:32:54.018+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='xkcd_comics' AIRFLOW_CTX_TASK_ID='create_table' AIRFLOW_CTX_EXECUTION_DATE='2025-02-14T10:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-02-14T10:00:00+00:00'
[2025-02-18T12:32:54.023+0000] {xkcd-comics-dag.py:41} INFO - comics Table created successfully!
[2025-02-18T12:32:54.025+0000] {xkcd-comics-dag.py:51} INFO - comics Table exists: True
[2025-02-18T12:32:54.025+0000] {python.py:194} INFO - Done. Returned value was: None
[2025-02-18T12:32:54.029+0000] {taskinstance.py:1398} INFO - Marking task as SUCCESS. dag_id=xkcd_comics, task_id=create_table, execution_date=20250214T100000, start_date=20250218T123253, end_date=20250218T123254
[2025-02-18T12:32:54.064+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2025-02-18T12:32:54.084+0000] {taskinstance.py:2776} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-02-18T12:35:32.314+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: xkcd_comics.create_table scheduled__2025-02-14T10:00:00+00:00 [queued]>
[2025-02-18T12:35:32.318+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: xkcd_comics.create_table scheduled__2025-02-14T10:00:00+00:00 [queued]>
[2025-02-18T12:35:32.318+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 4
[2025-02-18T12:35:32.323+0000] {taskinstance.py:1380} INFO - Executing <Task(PythonOperator): create_table> on 2025-02-14 10:00:00+00:00
[2025-02-18T12:35:32.325+0000] {standard_task_runner.py:57} INFO - Started process 179 to run task
[2025-02-18T12:35:32.326+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'xkcd_comics', 'create_table', 'scheduled__2025-02-14T10:00:00+00:00', '--job-id', '2', '--raw', '--subdir', 'DAGS_FOLDER/xkcd-comics-dag.py', '--cfg-path', '/tmp/tmp02umk6pu']
[2025-02-18T12:35:32.328+0000] {standard_task_runner.py:85} INFO - Job 2: Subtask create_table
[2025-02-18T12:35:32.334+0000] {logging_mixin.py:151} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-02-18T12:35:32.347+0000] {task_command.py:415} INFO - Running <TaskInstance: xkcd_comics.create_table scheduled__2025-02-14T10:00:00+00:00 [running]> on host 0ef9066179d4
[2025-02-18T12:35:32.384+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='xkcd_comics' AIRFLOW_CTX_TASK_ID='create_table' AIRFLOW_CTX_EXECUTION_DATE='2025-02-14T10:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-02-14T10:00:00+00:00'
[2025-02-18T12:35:32.391+0000] {xkcd-comics-dag.py:41} INFO - comics Table created successfully!
[2025-02-18T12:35:32.392+0000] {xkcd-comics-dag.py:51} INFO - comics Table exists: True
[2025-02-18T12:35:32.392+0000] {python.py:194} INFO - Done. Returned value was: None
[2025-02-18T12:35:32.397+0000] {taskinstance.py:1398} INFO - Marking task as SUCCESS. dag_id=xkcd_comics, task_id=create_table, execution_date=20250214T100000, start_date=20250218T123532, end_date=20250218T123532
[2025-02-18T12:35:32.426+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2025-02-18T12:35:32.436+0000] {taskinstance.py:2776} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-02-18T14:48:53.141+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: xkcd_comics.create_table scheduled__2025-02-14T10:00:00+00:00 [queued]>
[2025-02-18T14:48:53.144+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: xkcd_comics.create_table scheduled__2025-02-14T10:00:00+00:00 [queued]>
[2025-02-18T14:48:53.144+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 4
[2025-02-18T14:48:53.148+0000] {taskinstance.py:1380} INFO - Executing <Task(PythonOperator): create_table> on 2025-02-14 10:00:00+00:00
[2025-02-18T14:48:53.150+0000] {standard_task_runner.py:57} INFO - Started process 757 to run task
[2025-02-18T14:48:53.152+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'xkcd_comics', 'create_table', 'scheduled__2025-02-14T10:00:00+00:00', '--job-id', '2', '--raw', '--subdir', 'DAGS_FOLDER/xkcd-comics-dag.py', '--cfg-path', '/tmp/tmpxeyrvcya']
[2025-02-18T14:48:53.154+0000] {standard_task_runner.py:85} INFO - Job 2: Subtask create_table
[2025-02-18T14:48:53.178+0000] {task_command.py:415} INFO - Running <TaskInstance: xkcd_comics.create_table scheduled__2025-02-14T10:00:00+00:00 [running]> on host e3aab3801fb0
[2025-02-18T14:48:53.209+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='xkcd_comics' AIRFLOW_CTX_TASK_ID='create_table' AIRFLOW_CTX_EXECUTION_DATE='2025-02-14T10:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-02-14T10:00:00+00:00'
[2025-02-18T14:48:53.211+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/xkcd-comics-dag.py", line 26, in create_table
    conn = get_db_connection()
  File "/opt/airflow/dags/xkcd-comics-dag.py", line 22, in get_db_connection
    return psycopg2.connect(**DB_CONFIG)
  File "/home/airflow/.local/lib/python3.9/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "postgres" (172.18.0.2), port 5432 failed: FATAL:  database "xkcd" does not exist

[2025-02-18T14:48:53.214+0000] {taskinstance.py:1398} INFO - Marking task as UP_FOR_RETRY. dag_id=xkcd_comics, task_id=create_table, execution_date=20250214T100000, start_date=20250218T144853, end_date=20250218T144853
[2025-02-18T14:48:53.218+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 2 for task create_table (connection to server at "postgres" (172.18.0.2), port 5432 failed: FATAL:  database "xkcd" does not exist
; 757)
[2025-02-18T14:48:53.252+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-02-18T14:48:53.261+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
